### PR TITLE
Add Hexen 2 and Portal of Praevus

### PR DESCRIPTION
**Pull request by Slayer366**
Hexen II is a dark fantasy 1st-person shooter developed by Raven Software and published by id software.  Portal of Praevus features new levels, new enemies and a new playable character class, The Demoness.  The Hexen II pak0.pak and pak1.pak data files are required for Hexen 2 and pak3.pak is required to play the Portal of Praevus expansion.
This should run on RG351P, RG351M, RG351MP, and RG503 running ArkOS or 351Elec/AmberElec (and likely other devices and OSes).

### CODE REVIEW

**Comment by christianhaitian** [comment]
Sorry for my hold up in reviewing this.  ArkOS and AmberElec already include GZdoom for the Doom system setup which can play Hexen paks.  Can GZdoom play Hexen II as well?

**Comment by Slayer366** [comment]
Hexen II cannot as it runs on a modified Quake engine for its sequel to the first Hexen.  I should have noted in there that in order to play Portal of Praevus that you will not only need the pak3.pak for the expansion, but also requires the presence of the Hexen II base game pak0.pak and pak1.pak.  Let me know if you need me to make a change.

**Comment by Slayer366** [comment]
Oh, and don't sweat it.  I know you have other projects and things you're working on, too.  You've done a terrific job with PortMaster and especially ArkOS.  I'm not just saying that either, your excellent hard work has not gone unnoticed!  Keep up the good work.  I'd also like to share something with you that isn't port related on the device, but I'm not sure if you'd be interested or how you would like for me to send it to you (Discord?).

**Comment by christianhaitian** [comment]
This has been merged.  Please post the source you used for porting this to PortMaster so we can give proper credit in the wiki.

**Comment by Slayer366** [comment]
Gotcha.  Hexen 2 by sezero also has an SDL2 patch included for the source, but I had better results leaving it in SDL1 and using a wrapper (intermittent graphical issues).
Hexen 2 Source - https://github.com/sezero/uhexen2
SDL12-Compat (SDL1 to SDL2 wrapper) - https://github.com/libsdl-org/sdl12-compat

**Pull request merged**
