### PR TITLE
add Wordle SDL

### PR DESCRIPTION
**Pull request by christopher-roelofs**
Wordle SDL
========

Wordle SDL is a port of a clone of Wordle made with SDL.

Wordle is a web-based word game created and developed by Welsh software engineer Josh Wardle, and owned and published by The New York Times Company since 2022. 
Players have six attempts to guess a five-letter word, with feedback given for each guess in the form of colored tiles indicating when letters match or occupy the 
correct position.

Developer: Andrei Rafael (https://github.com/AndreiRafael)
URL: https://github.com/AndreiRafael/wordle_clone

Some logic for controls take from https://github.com/Rinnegatamante/wordle_clone

Tested on ArkOS, AmberELEC and uOS

CONTROLS

Dpad and and Left stick up/down = scroll through letters

A = Confirm letter selection
B = Undo letter selection
Y = Confirm word

Start + Select = Exit

### CODE REVIEW

**Comment by romadu** [comment]
On Chi using ArkOS, no input is working. This is resolved by adding `$ESUDO
chmod 666 /dev/uinput` to the shell script prior to launching the port.

On both Chi and rg503 using ArkOS, X button rather than Y button is used to
confirm the word.

d-pad left/right changes the letter. d-pad up causes the letter to ascend
rather than descend, and d-pad down causes the letter to descend rather
than ascend. Perhaps that could be swapped.

**Comment by romadu** [comment]
Updated .gptk file that supports key repeat (to quickly select letters) and
with X or Y to confirm the word

Updated script to correct issue with uinput

Reference to key repeat: https://github.com/romadu/gptokeyb#key-repeat

**Comment by christopher-roelofs** [comment]
@romadu do I need to make the changes or did you already do them?

**Comment by romadu** [comment]
I haven't made any changes, but you can use the files I provided. Not sure
about the up/down issue, or whether it matters, so that's not addressed at
the moment.

**Comment by romadu** [comment]
I mean I haven't updated the zip file, but I have changed the files that I
provided

**Comment by christopher-roelofs** [comment]
@romadu when you get a chance, I just committed.

**Comment by romadu** [comment]
Thanks, it works perfectly for me now. I note that README.txt and libs
folder have zero size, so maybe aren't required?

**Comment by christopher-roelofs** [comment]
I keep the libs folder and in the script incase a device needs them they can be added quickly and it doesn't seem to cause issues. The readme should have details. I will double check.

**Comment by christopher-roelofs** [comment]
And thanks for the suggestions. I've used the repeat functionality in gptokeyb before but I didn't even think about for this and it makes a huge difference.

**Comment by romadu** [comment]
This is a great addition to portmaster and one I will play from time to
time, so thanks for adding it

**Pull request merged**
