### PR TITLE
Add DungeonRush port 

### PR DESCRIPTION
**Pull request by lualiliu**
DungeonRush is a opensource game inspired by Snake, in pure C with SDL2. 
the source repo is https://github.com/rapiz1/DungeonRush
my fork is https://github.com/lualiliu/DungeonRush_PortMaster

### CODE REVIEW

**Comment by christianhaitian** [comment]
Hi, did you test it in ArkOS and JelOS or AmberElec yet?

**Comment by lualiliu** [comment]
> Hi, did you test it in ArkOS and JelOS or AmberElec yet?

It has been tested on jelos of RG503.

**Comment by romadu** [comment]
Do you have a compiled version that can be added to PortMaster? I couldn't see the compiled file to test it.

**Comment by lualiliu** [comment]
> Do you have a compiled version that can be added to PortMaster? I couldn't see the compiled file to test it.

First, clone my fork: https://github.com/lualiliu/DungeonRush_PortMaster
then, specify the toolchain at: CMakeLists.txt.
Pack the portmaster zip with the following command:

mkdir build
cd build
cmake ..
make
cd ..
./package.sh

**Comment by lualiliu** [comment]
> Do you have a compiled version that can be added to PortMaster? I couldn't see the compiled file to test it.

the compiled version in:
https://github.com/christianhaitian/PortMaster/blob/fd584e393bc73f5d345820a0fbc872aea866fdce/DungeonRush.zip

**Pull request closed without merging**
