### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by tfarray**
*Instructions :*
* Put your game SD card into your windows computer
* Launch powershell
* run the script

*Expected outcome :*
* screenshot will be copied to \ports\images
* A new file gamelist.xml will be created in the ports\ folder

*Requirements* 
* Portmaster needs to be intalled on the SD card

### CODE REVIEW

**Review by tfarray — COMMENTED** [review]
I have done a more recent commit, but I don't see the change here. I'm not sure I am submitting the correct version of the file

**Comment by JeodC** [comment]
This pull request is poorly named. I had no idea what it did until I checked the files changed. Further, as this is a powershell script that needs to run on a PC, I don't see why it would be added to this repo. I think you'd fare better promoting this in retro handheld discords where it may be picked up by PortMaster Team and added to the website.

That said, for clarity's sake, this is the gist of the ps1 script:

- Checks for SD card in PC
- Checks for `/roms/ports` folder (or `/roms2/ports` folder presumably for arkos)
- Checks if PortMaster is installed
- Gets a list of all .sh files in `ports` folder
- Pulls the port.screenshot.png and adds it to the `ports/images` folder
- Generates a gamelist.xml file based on the port.json

```
        "<game>
            <path>./$filename</path>
            <name>$($AllData[$filename].attr.title)</name>
            <desc>$($AllData[$filename].attr.desc)</desc>
            <developer>$($AllData[$filename].attr.porter -join ',')</developer>
            <genre>$($AllData[$filename].attr.genres -join ',')</genre>
            <image>$($AllData[$filename].screen)</image>
        </game>
        "
```
I have a couple comments here for improvement.

- The `developer` tag isn't necessarily going to be the porter. In fact most ports have multiple names under this tag. Usually the developer of the game itself is found in a Thanks section of the port.md file. Instead, you could place the porter information in the `publisher` tag in the xml.
- Most of the time screenscraper can find these ports anyway. What does this tool do that makes it superior to screenscraper?

**Comment by tfarray** [comment]
I am not used to github, and the pull request mechanism is not the same as for other platforms. Sorry for the bad naming.
I wasn't able to scrap ports with screenscraper, not only there wasn't any "ports" system on screenscraper, but the hash on the sh won't work neither.
I didn't know how to scrap them all at once, and wasn't able to scrap them.

But if you think this is of no use, you can dish it

**Comment by JeodC** [comment]
Again, I don't think it belongs in the PortMaster repo is all. I actually have my own repository for tools like this: https://github.com/JeodC/EmulationStation-Tools

It isn't official, so I just promote it every now and then in various Discord channels.

**Comment by tfarray** [comment]
I agree with your comments. Just wanted to share this small piece of code. Thanks for taking time to talk with me

**Pull request closed without merging**
