### PR TITLE
Add Quakespasm

### PR DESCRIPTION
**Pull request by Slayer366**
New Port for Quake supporting mods and Dimension of the Machine as well as GL4ES accelerated!

URL: https://github.com/Slayer366/quakespasm-for-GL4ES

Quakespasm

Instructions: 
Files needed

Quake:
quakespasm/id1/pak0.pak
quakespasm/id1/pak1.pak
quakespasm/id1/music/track02.ogg
quakespasm/id1/music/track03.ogg
quakespasm/id1/music/track04.ogg
quakespasm/id1/music/track05.ogg
quakespasm/id1/music/track06.ogg
quakespasm/id1/music/track07.ogg
quakespasm/id1/music/track08.ogg
quakespasm/id1/music/track09.ogg
quakespasm/id1/music/track10.ogg
quakespasm/id1/music/track11.ogg

Scourge of Armagon:
quakespasm/hipnotic/pak0.pak
quakespasm/hipnotic/music/track02.ogg
quakespasm/hipnotic/music/track03.ogg
quakespasm/hipnotic/music/track04.ogg
quakespasm/hipnotic/music/track05.ogg
quakespasm/hipnotic/music/track06.ogg
quakespasm/hipnotic/music/track07.ogg
quakespasm/hipnotic/music/track08.ogg
quakespasm/hipnotic/music/track09.ogg

Dissolution of Eternity:
quakespasm/rogue/pak0.pak
quakespasm/rogue/music/track02.ogg
quakespasm/rogue/music/track03.ogg
quakespasm/rogue/music/track04.ogg
quakespasm/rogue/music/track05.ogg
quakespasm/rogue/music/track06.ogg
quakespasm/rogue/music/track07.ogg
quakespasm/rogue/music/track08.ogg
quakespasm/rogue/music/track09.ogg

Dimension of the Past:
quakespasm/dopa/pak0.pak

Arcane Dimensions:
quakespasm/ad/pak0.pak
quakespasm/ad/pak1.pak
quakespasm/ad/pak2.pak

Dimension of the Machine:
quakespasm/QuakeEX.kpf
quakespasm/mg1/pak0.pak

Notes: Thanks to Ozkan Sezer (sezero) for the one of the most awesome and incredibly capable source ports for Quake supporting mods such as Arcane Dimensions and the latest 2021 Re-release, Dimension of the Machine.  It is recommended to use an RK3566 or faster CPU to run Arcane Dimensions or Dimension of the Machine.  Thanks to ptitseb for GL4ES.

Tested on ArkOS, 351Elec/AmberElec, RG351P, RG351M, RG351MP, RG353P, RG503

### CODE REVIEW

**Comment by christianhaitian** [comment]
Your port is missing the quakespasm.port.json

**Comment by Slayer366** [comment]
quakespasm.ports.json added 👍

**Comment by christianhaitian** [comment]
port images missing per the check.

**Comment by christopher-roelofs** [comment]
@Slayer366 Can you please add one more thing. A markdown file should be added to the markdown folder with the same name as the port zip (.md instead of .zip). These details will get rendered on the detail page of the new wiki for this port.

[Example file](https://raw.githubusercontent.com/PortsMaster/PortMaster-Website/main/content/markdown/example.md)

[Tool](https://portmaster.games/port-markdown.html) to help generate one if you need.

**Comment by Slayer366** [comment]
You got it.  That md generator you guys have there is pretty slick, btw.

**Comment by Slayer366** [comment]
Agreed.  Thank you for doing that for me.  Good lookin' out.

**Comment by tabreturn** [comment]
Quakespasm games run fine on RGB30 (JELOS), but there's no audio if I launch from EmulationStation. However, when launching from SSH, the audio plays fine. Maybe some permissions issue or something?

**Comment by Slayer366** [comment]
Gotcha.  I'll look into it.
    On Thursday, October 26, 2023 at 09:19:52 PM CDT, tabreturn ***@***.***> wrote:  
 
 


Quakespasm games run fine on RGB30 (JELOS), but there's no audio if I launch from EmulationStation. However, when launching from SSH, the audio plays fine. Maybe some permissions issue or something?

**Comment by christopher-roelofs** [comment]
@Slayer366 if you want quick feedback/testing, you can head over to the Portmaster discord and open a forum thread. We have a group of testers with a variety of devices willing to test ports. https://discord.gg/JxYBp9HTAY

**Pull request merged**
