### PR TITLE
Descent

### PR DESCRIPTION
**Pull request by dexwerx**
Descent 1 and 2 Portmaster ReadMe

* Based on the work from:
	https://www.dxx-rebirth.com
	https://github.com/krishenriksen/AnberPorts

* The builds seem to have SDL2 issues that were introduced when the DXX-Rebirth project migrated from SDL1 to SDL2. This breaks loading music from the original game data. The remastered music add-ons from DXX-rebirth are required if you want music.
	see https://www.dxx-rebirth.com/addons/

* game data files go in the Data folder

descent/Data/
	DESCENT.HOG
	DESCENT.PIG
	d1xr-hires.dxa		
		(optional https://www.dxx-rebirth.com/addons/)
	d1xr-sc55-music.dxa or d1xr-opl3-music.dxa
		(required for music https://www.dxx-rebirth.com/addons/ 
	
descent2/Data/
	d2xr-sc55-music.dxa or d2xr-opl3-music.dxa
		(required for music https://www.dxx-rebirth.com/addons/)
	descent2.ham
	descent2.hog
	descent2.s11
	descent2.s22
	alien1.pig	
	alien2.pig	
	fire.pig
	ice.pig
	water.pig
	groupa.pig	
	intro-h.mvl
	robots-h.mvl
	other-h.mvl

### CODE REVIEW

**Comment by romadu** [comment]
Have you configured controls? When I tried it now on ArkOS accelerate, etc isn't configured, which is the same as with my slightly later build (beta2-1641 v anberports beta2-1223). I don't know the game well enough to configure joystick controls, and received strong pushback against using keyboard-based controls through gptokeyb emulation.

**Comment by Roughtrade** [comment]
> Have you configured controls? When I tried it now on ArkOS accelerate, etc isn't configured, which is the same as with my slightly later build (beta2-1641 v anberports beta2-1223). I don't know the game well enough to configure joystick controls, and received strong pushback against using keyboard-based controls through gptokeyb emulation.

hi, would you be so kind to send me a link to your last descent builds beta2-1641 v anberports beta2-1223 i have already fixed the descent port controls, but i used the older files from dreivalt. 
Regards Peter ( snoopy / Amberelec )

**Comment by romadu** [comment]
The files are posted in Amberelec ports-dev discord

**Comment by Roughtrade** [comment]
> 

there is no ports-dev channel

**Comment by romadu** [comment]
Yes there is [image: image.png]

Please check with Cebion

**Comment by JeodC** [comment]
In case you're still around @dfreivald this is getting some updates on the Portmaster discord--if you'd like to get involved again.

**Comment by dfreivald** [comment]
Thanks for picking up the torch! I have a build machine set up, just haven't had time to work on it.

**Comment by JeodC** [comment]
> Thanks for picking up the torch! I have a build machine set up, just haven't had time to work on it.

Help us out! The rebirth build you supplied is from 2021 and pretty behind on updates.

https://discord.gg/TnE9hbgb

**Comment by JeodC** [comment]
Outdated, please use https://github.com/christianhaitian/PortMaster/pull/318

**Pull request closed without merging**
